Config = {}

-- フレームワーク設定
Config.Framework = 'qb-core' -- qb-core

-- 権限設定
-- サーバー側で以下の権限をチェックします：
-- 1. ACE権限: group.admin, qbcore.admin, admin
-- 2. QBCore権限: admin, mod, god
-- 3. ジョブ権限: admin
Config.Permission = {
    admin = 'admin', -- 管理者権限
    moderator = 'mod' -- モデレーター権限
}

-- コマンド設定
Config.Commands = {
    blipMenu = 'blips', -- ブリップメニューを開くコマンド
    adminOnly = true -- 管理者のみコマンド使用可能
}

-- ブリップ設定
Config.Blips = {
    maxBlips = 50, -- 最大ブリップ数
    defaultScale = 1.0, -- デフォルトサイズ
    defaultColor = 1, -- デフォルト色
    defaultSprite = 1 -- デフォルトスプライト
}

-- ブリップサイズ選択肢
Config.BlipScales = {
    {label = '極小 (0.5)', value = 0.5},
    {label = '小 (0.7)', value = 0.7},
    {label = '標準 (1.0)', value = 1.0},
    {label = '大 (1.3)', value = 1.3},
    {label = '特大 (1.5)', value = 1.5},
    {label = '最大 (2.0)', value = 2.0}
}

-- ブリップ色選択肢（完全版 0-85）
Config.BlipColors = {
    {label = '白', value = 0},
    {label = '赤', value = 1},
    {label = '緑', value = 2},
    {label = '青', value = 3},
    {label = '白（4）', value = 4},
    {label = '黄', value = 5},
    {label = '赤（6）', value = 6},
    {label = 'ライトブルー', value = 7},
    {label = 'ピンク', value = 8},
    {label = '赤（9）', value = 9},
    {label = 'ブラウン（10）', value = 10},
    {label = 'ライトピンク（11）', value = 11},
    {label = 'ライトブルー（12）', value = 12},
    {label = 'ライトグレー（13）', value = 13},
    {label = 'ライトグレー（14）', value = 14},
    {label = 'ライトグレー（15）', value = 15},
    {label = 'ライトグレー（16）', value = 16},
    {label = 'オレンジ', value = 17},
    {label = 'レッド（18）', value = 18},
    {label = '紫', value = 19},
    {label = 'グレー（20）', value = 20},
    {label = 'ダークブルー（21）', value = 21},
    {label = 'ダークブルー（22）', value = 22},
    {label = 'ダークブルー（23）', value = 23},
    {label = 'ブルー（24）', value = 24},
    {label = 'イエローグリーン（25）', value = 25},
    {label = 'イエロー（26）', value = 26},
    {label = 'オレンジ（27）', value = 27},
    {label = 'レッド（28）', value = 28},
    {label = 'ライトレッド（29）', value = 29},
    {label = 'ダークレッド（30）', value = 30},
    {label = 'ピンク（31）', value = 31},
    {label = 'イエロー（32）', value = 32},
    {label = 'ホワイト（33）', value = 33},
    {label = 'ライトブルー（34）', value = 34},
    {label = 'ライトイエロー（35）', value = 35},
    {label = 'ライトピンク（36）', value = 36},
    {label = 'ライトレッド（37）', value = 37},
    {label = 'ライトイエロー（38）', value = 38},
    {label = 'ホワイト（39）', value = 39},
    {label = 'ライトブルー（40）', value = 40},
    {label = 'ダークブルー（41）', value = 41},
    {label = 'ダークパープル（42）', value = 42},
    {label = 'ダークピンク（43）', value = 43},
    {label = 'ダークレッド（44）', value = 44},
    {label = 'ダークオレンジ（45）', value = 45},
    {label = 'ゴールド', value = 46},
    {label = 'ライトオレンジ（47）', value = 47},
    {label = 'ライトイエロー（48）', value = 48},
    {label = 'ライトグリーン（49）', value = 49},
    {label = 'ダークグリーン（50）', value = 50},
    {label = 'ライトブルー（51）', value = 51},
    {label = 'ライトパープル（52）', value = 52},
    {label = 'ダークパープル（53）', value = 53},
    {label = 'ダークグレー', value = 54},
    {label = 'ライトグレー', value = 55},
    {label = 'ライトピンク（56）', value = 56},
    {label = 'ライトグリーン（57）', value = 57},
    {label = 'ライトブラウン（58）', value = 58},
    {label = 'ライトパープル（59）', value = 59},
    {label = 'ダークパープル（60）', value = 60},
    {label = 'ライトオレンジ（61）', value = 61},
    {label = 'ライトブルー（62）', value = 62},
    {label = 'ダークピンク（63）', value = 63},
    {label = 'ライトピンク（64）', value = 64},
    {label = 'ライトイエロー（65）', value = 65},
    {label = 'ライトブルー（66）', value = 66},
    {label = 'ライトグリーン（67）', value = 67},
    {label = 'ライトブラウン（68）', value = 68},
    {label = 'ライトパープル（69）', value = 69},
    {label = 'ダークグリーン（70）', value = 70},
    {label = 'ライトブルー（71）', value = 71},
    {label = 'ライトパープル（72）', value = 72},
    {label = 'ダークピンク（73）', value = 73},
    {label = 'ライトピンク（74）', value = 74},
    {label = 'ライトグリーン（75）', value = 75},
    {label = 'ライトブラウン（76）', value = 76},
    {label = 'ライトイエロー（77）', value = 77},
    {label = 'ライトブルー（78）', value = 78},
    {label = 'ダークピンク（79）', value = 79},
    {label = 'ライトオレンジ（80）', value = 80},
    {label = 'ライトイエロー（81）', value = 81},
    {label = 'ライトピンク（82）', value = 82},
    {label = 'ライトブルー（83）', value = 83},
    {label = 'ネットプレイヤー1', value = 84},
    {label = 'ネットプレイヤー2', value = 85}
}

-- ブリップスプライト選択肢（FiveM公式ドキュメントに基づく完全版）
Config.BlipSprites = {
    -- 基本アイコン
    {label = 'ドット', value = 1},
    {label = 'レーダー半径アウトライン', value = 10},
    {label = '警察飛行機', value = 16},
    {label = '計画場所', value = 48},
    {label = 'FBI警官', value = 106},
    {label = 'フィナーレ銀行強盗', value = 107},
    {label = '銀行', value = 108},
    {label = 'マイケル家族追放', value = 112},
    {label = 'ニースハウス強盗', value = 113},
    {label = '地方銀行強盗', value = 118},
    {label = 'トレバー家族追放', value = 123},
    {label = 'マイケル・トレバー家族', value = 124},
    {label = '警察署（青）', value = 137},
    {label = '犯罪者保存車両', value = 139},
    {label = '目標（黄）', value = 146},
    {label = '武器アサルトライフル', value = 150},
    {label = 'ギャング警官パートナー', value = 171},
    {label = 'プロパティ買収', value = 176},
    {label = 'ギャングメキシカンハイライト', value = 177},
    {label = 'ギャングバイカーハイライト', value = 178},
    {label = 'トライアスロンサイクリング', value = 179},
    {label = 'トライアスロン水泳', value = 180},
    {label = 'プロパティ買収バイカー', value = 181},
    {label = 'プロパティ買収警察', value = 182},
    {label = 'プロパティ買収ヴァゴス', value = 183},
    {label = '手錠キー（バイカー）', value = 186},
    {label = '手錠キー（ヴァゴス）', value = 187},
    {label = '手錠クローズ（バイカー）', value = 188},
    {label = '手錠クローズ（ヴァゴス）', value = 189},
    {label = 'ATM', value = 207},
    {label = 'トレバー家族（グレー）', value = 208},
    {label = 'トレバー家族（赤）', value = 209},
    {label = 'フランクリン家族（グレー）', value = 210},
    {label = 'フランクリン家族（青）', value = 211},
    {label = 'ギャング車両（バイカー）', value = 226},
    {label = 'ギャング車両（警察）', value = 227},
    {label = 'ギャング車両（ヴァゴス）', value = 228},
    {label = 'ギャング警察ハイライト', value = 233},
    {label = '武器取引（空中）', value = 251},
    {label = 'プレイヤー状態：逮捕', value = 252},
    {label = 'プレイヤー状態：拘留', value = 253},
    {label = 'プレイヤー状態：運転中', value = 254},
    {label = 'プレイヤー状態：キーホルダー', value = 255},
    {label = 'プレイヤー状態：パートナー', value = 256},
    {label = '領域ロック', value = 275},
    {label = '犯罪車盗難（警察）', value = 289},
    {label = '犯罪車盗難（バイカー）', value = 290},
    {label = '犯罪車盗難（ヴァゴス）', value = 291},
    {label = '友人コメディクラブ', value = 297},
    {label = '友人ストリップクラブ', value = 300},
    {label = '友人ライブ音楽', value = 301},
    {label = '射撃場銃店', value = 313},
    {label = 'ミッション（バイカー1）', value = 327},
    {label = 'ミッション（バイカー1-2）', value = 328},
    {label = 'ミッション（バイカー2）', value = 329},
    {label = 'ミッション（バイカー2-4）', value = 330},
    {label = 'ミッション（バイカー2-8）', value = 331},
    {label = 'ミッション（バイカー2-12）', value = 332},
    {label = 'ミッション（バイカー2-16）', value = 333},
    {label = 'ミッション（警察1-2）', value = 335},
    {label = 'ミッション（警察2-4）', value = 337},
    {label = 'ミッション（警察2-8）', value = 338},
    {label = 'ミッション（警察2-12）', value = 339},
    {label = 'ミッション（警察2-16）', value = 340},
    {label = 'ミッション（ヴァゴス1-2）', value = 342},
    {label = 'ミッション（ヴァゴス2-4）', value = 344},
    {label = 'ミッション（ヴァゴス2-8）', value = 345},
    {label = 'ミッション（ヴァゴス2-12）', value = 346},
    {label = 'ミッション（ヴァゴス2-16）', value = 347},
    {label = '売り物件', value = 350},
    {label = 'ギャング攻撃パッケージ', value = 351},
    {label = 'ガソリンスタンド', value = 361},
    {label = 'スポーン地点ピックアップ', value = 365},
    {label = '売りヘリパッド', value = 370},
    {label = '売りビジネス', value = 375},
    {label = '車両デスマッチ', value = 380},
    {label = 'クレートドロップ背景', value = 391},
    {label = '緑＆ネットプレイヤー1', value = 392},
    {label = '緑＆ネットプレイヤー2', value = 393},
    {label = '緑＆ネットプレイヤー3', value = 394},
    {label = '緑＆フレンドリー', value = 395},
    {label = 'ネットプレイヤー1＆2', value = 396},
    {label = 'ネットプレイヤー1＆3', value = 397},
    {label = 'クリエイター方向', value = 399},
    {label = 'キャプチャーザフラッグ', value = 408},
    {label = 'ラストチームスタンディング', value = 409},
    {label = 'キャプチャーザフラッグベース', value = 411},
    {label = 'キャプチャーザフラッグアウトライン', value = 413},
    {label = 'キャプチャーザフラッグベースノーバッグ', value = 414},
    {label = '賞金ヒット内部', value = 418},
    {label = 'キャプチャーザUSAフラッグ', value = 419},
    {label = 'キャプチャーザUSAフラッグアウトライン', value = 420},
    {label = 'アーバンウォーフェア対戦', value = 437},
    {label = 'キングオブザキャッスル', value = 438},
    {label = 'エッジクロスザライン', value = 444},
    {label = 'ベリーオブザビースト', value = 461},
    {label = 'ピックアップスローモーション', value = 466},
    {label = '売り倉庫', value = 474},
    {label = 'エリアアウトライン', value = 482},
    {label = 'ピックアップアクセラレーター', value = 483},
    {label = 'ピックアップ起爆装置', value = 485},
    {label = '生産クラック', value = 497},
    {label = '生産偽ID', value = 498},
    {label = '生産マネー', value = 500},
    {label = '倉庫車両', value = 524},
    {label = '警察署ドロップオフ', value = 526},
    {label = 'ピックアップロケットブースト', value = 547},
    {label = 'ピックアップホーミングロケット', value = 548},
    {label = 'ピックアップマシンガン', value = 549},
    {label = 'ピックアップパラシュート', value = 550},
    {label = '敵対バンカー', value = 565},
    {label = 'NHPタレット制御', value = 606},
    {label = 'NHP MGミール回転', value = 607},
    {label = 'NHP MGミール静的', value = 608},
    {label = 'ACSRレース目標', value = 610},
    {label = 'ACSRレースホットリング', value = 611},
    {label = 'バットクラブプロパティ', value = 614},
    {label = 'ピックアップDTBヘルス', value = 621},
    {label = 'ピックアップDTB爆発増加', value = 622},
    {label = 'ピックアップDTB爆発減少', value = 623},
    {label = 'ピックアップDTB爆弾増加', value = 624},
    {label = 'ピックアップDTB爆弾減少', value = 625},
    {label = 'アリーナRCワークショップ', value = 647},
    {label = 'キングオブザヒル', value = 674},
    {label = 'キングオブザヒルチーム', value = 675},
    {label = '輸送コンテナ', value = 677},
    {label = 'カジノテーブルゲーム', value = 680},
    {label = 'カジノコンシェルジュ', value = 682},
    {label = 'カジノ競馬', value = 684},
    {label = '敵対フィーチャー', value = 685},
    {label = 'レトロスポーツカー', value = 756},
    {label = 'フォールディングウィングジェット', value = 758},
    {label = 'アイランド強盗準備', value = 765},
    {label = 'オートショッププロパティ', value = 779},
    {label = '車強盗ボード', value = 783},
    {label = '車強盗準備', value = 784},
    {label = 'ストリートレースシリーズ', value = 785},
    {label = 'カーミートオーガナイザー', value = 787},
    {label = '賞金収集品', value = 789},
    {label = '映画収集品', value = 790},
    {label = '建設服装', value = 801},
    {label = '強盗島利用不可', value = 803},
    {label = '強盗ダイヤモンド利用不可', value = 804},
    {label = '強盗ドゥームズデイ利用不可', value = 805},
    {label = '売り車両', value = 810},
    {label = 'セキュリティ契約', value = 813},
    {label = '爆発物', value = 822},
    {label = 'ラグジュアリーカーショールーム', value = 830},
    {label = 'カーショールームシメオン', value = 832},
    {label = 'コミュニティシリーズ', value = 835},
    {label = 'クラブハウス契約', value = 837},
    {label = 'デッドドロップパッケージ', value = 842},
    {label = '倉庫ジャガロ', value = 847},
    {label = '倉庫ジャガロダックス', value = 848},
    {label = '複数階ガレージ', value = 856},
    {label = '差し押さえ資産販売', value = 857},
    {label = 'オーバーレイ売り準備', value = 863},
    {label = 'オーバーレイ供給不足', value = 864},
    {label = '強盗準備機器', value = 868},
    {label = '強盗準備オーバーレイ', value = 869},
    {label = 'CCTV作業台', value = 874},
    {label = '列車信号（緑）', value = 882},
    {label = '列車信号（赤）', value = 883},
    {label = 'オフィス輸送機', value = 884},
    {label = 'ヤンクトンサバイバル', value = 885},
    {label = '撮影スケジュール', value = 888},
    {label = '航空母艦', value = 890},
    {label = '保釈債券事務所', value = 893},
    {label = 'ゾンビ近接', value = 896},
    {label = '動物憑依', value = 898},
    {label = '衣料工場売り', value = 901},
    {label = '衣料工場機器', value = 902},
    {label = 'フィールドハンガー売り', value = 904},
    {label = 'ヘリ昇降弾薬', value = 906},
    {label = 'ヘリ昇降装甲', value = 907},
    {label = 'ヘリ昇降爆発物', value = 908},
    {label = 'ヘリ昇降アップグレード', value = 909},
    {label = 'ヘリ昇降武器', value = 910},
    {label = '潜水艦ミサイル', value = 912},
    {label = 'プロペラエンジン', value = 913},
    {label = 'フィールドハンガー割引', value = 919},
    {label = '衣料工場割引', value = 920},
    {label = '武器ガセンバーグスイーパー', value = 921},
    
    -- よく使用される基本アイコン
    {label = '家', value = 40},
    {label = 'チェックポイント', value = 38},
    {label = '星', value = 42},
    {label = 'ガレージ', value = 50},
    {label = 'ショップ', value = 52},
    {label = '車', value = 56},
    {label = '警察署', value = 60},
    {label = '病院', value = 61},
    {label = '理髪店', value = 71},
    {label = '服屋', value = 73},
    {label = 'ダイヤモンド', value = 84},
    {label = 'レストラン', value = 93},
    {label = '武器店', value = 110},
    {label = 'クラウン', value = 205},
    {label = 'アパート', value = 475}
}

-- データベーステーブル名
Config.Database = {
    tableName = 'ng_blips'
}

-- 通知設定
Config.Notifications = {
    success = {
        blipCreated = 'ブリップが作成されました',
        blipUpdated = 'ブリップが更新されました',
        blipDeleted = 'ブリップが削除されました'
    },
    error = {
        maxBlipsReached = '最大ブリップ数に達しています',
        noPermission = '権限がありません',
        blipNotFound = 'ブリップが見つかりません',
        invalidData = '無効なデータです'
    },
    info = {
        blipMenuOpened = 'ブリップメニューを開きました'
    }
}

-- UI設定
Config.UI = {
    menuTitle = 'NG Blip Creator',
    menuSubtitle = 'ブリップ作成・管理システム'
}